name: Publish to Cargo

on:
  push:
    branches: [main]

jobs:
  publish:
    name: "publish"
    runs-on: ubuntu-latest
    environment: cargo_env
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          path: "./dify-client"
          dry-run: ${{ github.ref_name != 'main' }}
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
